import React from 'react';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';
import type { DietPlan } from '../types.ts';
import { Download, RefreshCw, Check } from 'lucide-react';

interface DietPlanResultProps {
    plan: DietPlan;
    onReset: () => void;
}

export const DietPlanResult: React.FC<DietPlanResultProps> = ({ plan, onReset }) => {
    const generatePDF = () => {
        const doc = new jsPDF();

        // Add decorative header
        doc.setFillColor(212, 175, 55); // Gold
        doc.rect(0, 0, 210, 20, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFont("times", "bold");
        doc.setFontSize(22);
        doc.text("Ayursutra - Personalized Diet Plan", 105, 13, { align: "center" });

        // Content
        doc.setTextColor(46, 74, 61); // Deep Green
        doc.setFont("times", "bold");
        doc.setFontSize(18);
        doc.text(`Your Dominant Dosha: ${plan.dosha}`, 20, 40);

        doc.setFont("times", "normal");
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        const splitDesc = doc.splitTextToSize(plan.description, 170);
        doc.text(splitDesc, 20, 50);

        let yPos = 70;

        // Foods to Eat
        doc.setFont("times", "bold");
        doc.setTextColor(46, 74, 61);
        doc.text("Foods to Favor:", 20, yPos);
        yPos += 10;
        doc.setFont("times", "normal");
        doc.setTextColor(0, 0, 0);
        plan.foodsToEat.forEach(food => {
            doc.text(`• ${food}`, 25, yPos);
            yPos += 7;
        });

        yPos += 10;

        // Foods to Avoid
        doc.setFont("times", "bold");
        doc.setTextColor(192, 64, 0); // Terracotta/Reddish
        doc.text("Foods to Minimize:", 20, yPos);
        yPos += 10;
        doc.setFont("times", "normal");
        doc.setTextColor(0, 0, 0);
        plan.foodsToAvoid.forEach(food => {
            doc.text(`• ${food}`, 25, yPos);
            yPos += 7;
        });

        yPos += 10;

        // Lifestyle Tips
        doc.setFont("times", "bold");
        doc.setTextColor(46, 74, 61);
        doc.text("Lifestyle Recommendations:", 20, yPos);
        yPos += 10;
        doc.setFont("times", "normal");
        doc.setTextColor(0, 0, 0);
        plan.lifestyleTips.forEach(tip => {
            doc.text(`• ${tip}`, 25, yPos);
            yPos += 7;
        });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(128, 128, 128);
        doc.text("Generated by Ayursutra", 105, 280, { align: "center" });

        doc.save(`Ayursutra_Diet_Plan_${plan.dosha}.pdf`);
    };

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full max-w-3xl mx-auto p-6"
        >
            <div className="bg-white/90 backdrop-blur-md rounded-xl ancient-border p-8 md:p-12 text-center">
                <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ delay: 0.2 }}
                >
                    <h2 className="text-3xl md:text-4xl font-heading text-secondary mb-4">
                        Your Ayurvedic Constitution
                    </h2>
                    <div className="inline-block px-8 py-3 bg-primary/10 rounded-full border border-primary/30 mb-6">
                        <span className="text-4xl font-heading text-primary font-bold">{plan.dosha}</span>
                    </div>
                    <p className="text-lg text-gray-700 mb-8 leading-relaxed font-body">
                        {plan.description}
                    </p>
                </motion.div>

                <div className="grid md:grid-cols-2 gap-8 text-left mb-12">
                    <div className="bg-green-50 p-6 rounded-lg border border-green-100">
                        <h3 className="font-heading text-xl text-secondary mb-4 flex items-center">
                            <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                            Foods to Favor
                        </h3>
                        <ul className="space-y-2">
                            {plan.foodsToEat.slice(0, 5).map((food, i) => (
                                <li key={i} className="text-gray-700 flex items-start">
                                    <Check className="w-4 h-4 text-green-500 mr-2 mt-1 shrink-0" />
                                    {food}
                                </li>
                            ))}
                        </ul>
                    </div>

                    <div className="bg-red-50 p-6 rounded-lg border border-red-100">
                        <h3 className="font-heading text-xl text-accent mb-4 flex items-center">
                            <span className="w-2 h-2 bg-red-500 rounded-full mr-2"></span>
                            Foods to Minimize
                        </h3>
                        <ul className="space-y-2">
                            {plan.foodsToAvoid.slice(0, 5).map((food, i) => (
                                <li key={i} className="text-gray-700 flex items-start">
                                    <span className="w-4 h-4 text-red-400 mr-2 mt-1 shrink-0 text-center leading-none">×</span>
                                    {food}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <button
                        onClick={generatePDF}
                        className="btn-primary flex items-center justify-center gap-2"
                    >
                        <Download className="w-5 h-5" />
                        Download Full Plan (PDF)
                    </button>

                    <button
                        onClick={onReset}
                        className="btn-secondary flex items-center justify-center gap-2"
                    >
                        <RefreshCw className="w-5 h-5" />
                        Retake Questionnaire
                    </button>
                </div>
            </div>
        </motion.div>
    );
};
